26 create custom json button
bftawfik/simple-quiz pull request #30
Opened 2024-02-25 13:56 UTC by MennaHisham

2024-02-25 14:27 UTC, NourElturky commented on src/app/addjson/_components/alertMessage/AlertMessage.tsx
> +  //   const router = useRouter();
if you aren't using it please delete it

2024-02-25 14:27 UTC, NourElturky commented on src/app/_components/startScreen/StartScreen.tsx
> -import Link from 'next/link';
"use client

2024-02-25 14:27 UTC, NourElturky commented on src/app/_components/svg/NextArrow.tsx
>  export const NextArrow: React.FC<SvgProps> = ({
delete it

2024-02-25 15:16 UTC, saraEid77 approved these changes

2024-02-26 09:05 UTC, fadyfawzydev requested changes

2024-02-26 09:05 UTC, fadyfawzydev commented on src/app/_components/startScreen/StartScreen.tsx
> +      <Button text="Custom JSON" onClick={() => handleClick('/addjson')} />
use link instead of Buttons

2024-02-26 09:05 UTC, fadyfawzydev commented on src/app/success/page.tsx
> +      <Button text="Back to Homepage" onClick={() => router.push('/')} />
Should be Link normally

2024-02-26 09:17 UTC, merged